version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    volumes:
      - /data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - /data/logstash:/etc/logstash/conf.d
      - /data/logs:/logfiles
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - /data/kibana:/opt/kibana/config/
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  cerebro:
    build: cerebro/
    networks:
      - docker_elk
    ports:
      - "127.0.0.1:9000:9000"
    depends_on:
      - elasticsearch
networks:
  docker_elk:
    driver: bridge
